#!/bin/bash

FAILED=0
FMTRESULT=0
diff="$(cargo fmt -- --check $file)"

if grep --quiet "^[-+]" <<< "$diff"; then
    FMTRESULT=1
fi

if [ ${FMTRESULT} != 0 ]; then
  FAILED=1
  echo "${FAILURE}"
  echo "${diff}" | sed 's/Using rustfmt config file.*$/d/'
fi

exit ${FAILED}
